### ISSUE TITLE
Two minor issues on small screens

### ISSUE THREAD

**Issue by msyriac** [Stony-Brook-Astronomy/astro_webpage#11]
Here's how the webpage looks on my phone:

![screenshot_2016-08-25-22-59-37](https://cloud.githubusercontent.com/assets/3674397/17992923/52adf3ae-6b19-11e6-81a1-e959b70cd196.png)
1. The hamburger menu icon touches "Stony Brook Astronomy" a bit
2. This is probably because the text and banners are placeholders, but the user is reminder three times that they are looking at something related to "Stony Brook Astronomy"

I think the new design is a huge step up though!

**Comment by zingale** [comment]
that change 0655c42955c6933f2cc7e1fd908039513da3fb0f puts the news feed above the last Stony Brook heading when on mobile.
