### ISSUE TITLE
Alignment of main content

### ISSUE THREAD

**Issue by msyriac** [Stony-Brook-Astronomy/astro_webpage#12]
Everything on the webpage is center aligned, except for the "Astronomy at Stony Brook" and "News" elements which are left aligned:

![screenshot 2016-08-25 at 11 17 08 pm](https://cloud.githubusercontent.com/assets/3674397/17992998/334ec5b4-6b1a-11e6-8562-a01ff18bea53.png)

**Comment by zingale** [comment]
I think that the way this style works is that divs that are full width (12u in the skel format) are centered.  And divs that are < 12 u are left justified. I'll leave it like this for now.
