### ISSUE TITLE
Observational Cosmology: "Cosmology" or "Observational Astronomy" ?

### ISSUE THREAD

**Issue by anjavdl** [Stony-Brook-Astronomy/astro_webpage#3]
I fit under both - are you going to make me pick?

**Comment by zingale** [comment]
I agree it is becoming hard to put people into a single category anymore.  One thing I can do instead is just put everyone together uncategorized.

I am happy to use alternate categories if people can suggest.

**Comment by anjavdl** [comment]
I'd be fine with non-categorization.

Right now, it's a mix of "how" we study things (observations / theory+simulations) and "what" we study (cosmology).  If we want to keep categories, then I would prefer to split by "what" we study.  For example, "Cosmology and extragalactic astronomy" vs. "Stars and compact objects" would define everyone, except that Rosalba can belong to either one.

**Comment by zingale** [comment]
I think it's more complicated than that.  I think what i study is
"algorithms".

I'll try out an uncategorized display.

**Comment by zingale** [comment]
take a look now -- I added a section at the top that shows research interests by the "what" (and in this definition, I consider algorithms to be a "what"), and then have us alphabetized below.

**Comment by neelimasehgal** [comment]
hi mike - I think Kenneth Lanzetta belongs under Extragalactic Astronomy and not Cosmology.

**Comment by neelimasehgal** [comment]
Also, is there a typo in this: "OUR GROUP SPANS A WIDE RANGE OF RESEARCH INTERESTED, GALACTIC..." ?

**Comment by anjavdl** [comment]
I like the new layout!  :-)

**Comment by zingale** [comment]
thanks.  I'll consider this closed
