### ISSUE TITLE
Office locations

### ISSUE THREAD

**Issue by dswesty** [Stony-Brook-Astronomy/astro_webpage#4]
Nice job on the re-write!

  In the new "People" section it states:  
    "Our offices are located in the Earth and Space Sciences building, on the 4th floor (marked PH in the elevator)."

  I suggest it would be less confusing to say:

   "Our offices are located in the Earth and Space Sciences building penthouse  (use the PH button in the elevator) which is also known as the 4th floor."

  That's just my two cents!

**Comment by zingale** [comment]
thanks Doug.  Will do
